version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: PostgresDB
      MYSQL_PORT: 5432
      MYSQL_DB: questiondb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    command: [ "java", "-jar", "app.jar" ]
    depends_on:
      MysqlDB:
        condition: service_healthy



  MysqlDB:
    image: mysql/mysql-server:8.0.25
    container_name: MysqlDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB: questiondb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 2s
      retries: 30