name: Build, test and publish Docker image

on:
  push:
    branches:
      - master


# Set environment variables for pushing Docker image to GitHub Container Registry
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  # Build jar, run unit tests and upload jar as artifact
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out the repository
      - uses: actions/checkout@v3

      # Cache the gradle dependencies and wrapper to speed up the build
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run build and run unit tests
      - name: Run build
        run: ./gradlew build

      # Upload artifact to use in the next job
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/ciditest.jar